### 导入商品
POST http://localhost:9001/imooc/commerce-goods-service/async-goods/import-goods
Content-Type: application/json
commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJjb21tZXJjZS11c2VyIjoie1wiaWRcIjoxMCxcInVzZXJuYW1lXCI6XCJxcXFcIn0iLCJqdGkiOiI4YTQwNmY5Ny1iZWM4LTRhYTUtOWMxNy1lZTFjMTBjNTdmYjIiLCJleHAiOjE2NTQ1MzEyMDB9.C-xbbrKDElKH4EISQAyuJS_06Whyv8Qy_J9PgQaqEYHaS8c4ut1s-10zv4SVLtN0f_97tzLYu89VrTfJ5_WdKlfSxVX7DUw8bb9iKNOaArxKB6jbM8DjF2AyA7nZTdraVTMNw1RH2SPh02aMxLAThy9YJAeMCu-JedUmkmaio5qQtOBJD7a_VQ9kkyrAhdk7PiPI1B98sM2inLa-zeE9Mkr4DDPG5BDG7o-keibtC2sXezQKD8fsCHx7qGQQ8Zf7Z4kJPod1NZrIVWp3DHIalTkcAZr9Ajc3SA7LrqQjfi9iStLi2WjBS50iHqmxqZykxaL9GA_YWDhuFPMw-sig8g

[
  {
    "goodsCategory": "10001",
    "brandCategory": "20001",
    "goodsName": "iphone 11",
    "goodsPic": "",
    "goodsDescription": "苹果手机",
    "price": 100000,
    "supply": 2000000,
    "goodsProperty": {
      "size": "12cm * 6.5cm",
      "color": "绿色",
      "material": "金属机身",
      "pattern": "纯色"
    }
  },
  {
    "goodsCategory": "10001",
    "brandCategory": "20001",
    "goodsName": "iphone 12",
    "goodsPic": "",
    "goodsDescription": "苹果手机",
    "price": 150000,
    "supply": 2000000,
    "goodsProperty": {
      "size": "12cm * 6.5cm",
      "color": "绿色",
      "material": "金属机身",
      "pattern": "纯色"
    }
  },
  {
    "goodsCategory": "10001",
    "brandCategory": "20001",
    "goodsName": "iphone 13",
    "goodsPic": "",
    "goodsDescription": "苹果手机",
    "price": 160000,
    "supply": 2000000,
    "goodsProperty": {
      "size": "12cm * 6.5cm",
      "color": "绿色",
      "material": "金属机身",
      "pattern": "纯色"
    }
  }
]


### 查询导入商品状态
GET http://localhost:9001/imooc/commerce-goods-service/async-goods/task-info?taskId=ff132302-b9f9-4dac-a390-a8f0b399c6d6
Accept: application/json
commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJjb21tZXJjZS11c2VyIjoie1wiaWRcIjoxMCxcInVzZXJuYW1lXCI6XCJxcXFcIn0iLCJqdGkiOiI4YTQwNmY5Ny1iZWM4LTRhYTUtOWMxNy1lZTFjMTBjNTdmYjIiLCJleHAiOjE2NTQ1MzEyMDB9.C-xbbrKDElKH4EISQAyuJS_06Whyv8Qy_J9PgQaqEYHaS8c4ut1s-10zv4SVLtN0f_97tzLYu89VrTfJ5_WdKlfSxVX7DUw8bb9iKNOaArxKB6jbM8DjF2AyA7nZTdraVTMNw1RH2SPh02aMxLAThy9YJAeMCu-JedUmkmaio5qQtOBJD7a_VQ9kkyrAhdk7PiPI1B98sM2inLa-zeE9Mkr4DDPG5BDG7o-keibtC2sXezQKD8fsCHx7qGQQ8Zf7Z4kJPod1NZrIVWp3DHIalTkcAZr9Ajc3SA7LrqQjfi9iStLi2WjBS50iHqmxqZykxaL9GA_YWDhuFPMw-sig8g

