
### 查询服务实例信息
GET http://localhost:8000/commerce-nacos-client/nacos-client/service-instance
Accept: application/json


### 查看 sleuth 跟踪信息
GET http://localhost:9001/imooc/commerce-nacos-client/sleuth/trace-info
Accept: application/json
commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJjb21tZXJjZS11c2VyIjoie1wiaWRcIjoxMixcInVzZXJuYW1lXCI6XCJlZWVcIn0iLCJqdGkiOiJkZmE1MTZjZS0zNWQzLTQzNTYtYTE5Yy1hYjkxYTNhYTYzZDQiLCJleHAiOjE2NTQwMTI4MDB9.LiBMpwR7j9roD0EVEZFD4HC2CMmBXz6NYv5Q2nKSCLZajGmSY6yhYGB_eqTujv8V_2Nt-6TAMe0h0eNfUDGMdQ0l5zShMTq6bsqAyRtJbvbxutBFoR2YA-4Uzc_Ze5BCdM3TVVFiZs-IF4lrwcX109jtWtmb1SbCYW84rZkaoBBJqWigwhndBsPDYV1kRnXSsJk7Op9e3rOHb6THAkXdTYPR0aZsYMbmMr7TkdIYaj5hq-mbABRQE-LSrl4UBXYxX95Dj1YJrYnepndmpkB37MXnRl30LTBumSTNNEMRL0a8O6EPRxaeE9tZ40OAPeuqxYRCal69vJm4sKbkR0QkiQ
token: imooc

