
### 创建订单
POST http://localhost:9001/imooc/commerce-order-service/order/create-order
Content-Type: application/json
Accept: application/json
commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJjb21tZXJjZS11c2VyIjoie1wiaWRcIjoxMCxcInVzZXJuYW1lXCI6XCJxcXFcIn0iLCJqdGkiOiI5MTEwM2I3My0zOTY2LTQxZjctYTI3OC00YzA4YzFmYzUyMTgiLCJleHAiOjE2NTQ5NjMyMDB9.VbPkqOnUPxp60VISudIsqhn877iY4ycZ96r505KQYUOvdFPgTf73TpCgZBoGe3sqYOaA0Q1FiRMPx3h66DhMfrEMWARcW0Ei-3UOQIGeiJwPb2vBh9rTdO0cqvU3O6DxdJxXwnPfNwH7ITwcfgoVlViZ-UFSy0r_xM-Dw9gAmnFPFYsBrR1N1I_PqzqRsLMomb165kkdx7VvSwL0Ow17qOD0HwsOEkqnRONVptzVp9G_nXCZldrup2MjE2P2dLOg58ABJtqlwLNMn3ov1VF5khuY7CawP5LVjStIUwKLSaltr3LBoOJI3W3jz8jNIPv7QQTT4UhWLEiUpVIJu0WR1w

{
  "userAddress": 1,
  "orderItems": [
    {
      "goodsId": 10,
      "count": 1
    },
    {
      "goodsId": 11,
      "count": 2
    }
  ]
}


### 查询订单
GET http://localhost:9001/imooc/commerce-order-service/order/get-simple-order-detail?page=1
Accept: application/json
commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJjb21tZXJjZS11c2VyIjoie1wiaWRcIjoxMCxcInVzZXJuYW1lXCI6XCJxcXFcIn0iLCJqdGkiOiI5MTEwM2I3My0zOTY2LTQxZjctYTI3OC00YzA4YzFmYzUyMTgiLCJleHAiOjE2NTQ5NjMyMDB9.VbPkqOnUPxp60VISudIsqhn877iY4ycZ96r505KQYUOvdFPgTf73TpCgZBoGe3sqYOaA0Q1FiRMPx3h66DhMfrEMWARcW0Ei-3UOQIGeiJwPb2vBh9rTdO0cqvU3O6DxdJxXwnPfNwH7ITwcfgoVlViZ-UFSy0r_xM-Dw9gAmnFPFYsBrR1N1I_PqzqRsLMomb165kkdx7VvSwL0Ow17qOD0HwsOEkqnRONVptzVp9G_nXCZldrup2MjE2P2dLOg58ABJtqlwLNMn3ov1VF5khuY7CawP5LVjStIUwKLSaltr3LBoOJI3W3jz8jNIPv7QQTT4UhWLEiUpVIJu0WR1w



