
### 发送一个请求
POST http://localhost:9001/imooc/commerce-nacos-client/communication/rest-template
Content-Type: application/json
Commerce-User: eyJhbGciOiJSUzI1NiJ9.eyJjb21tZXJjZS11c2VyIjoie1wiaWRcIjoxMCxcInVzZXJuYW1lXCI6XCJxcXFcIn0iLCJqdGkiOiI0MmNkZTUwMS01MjZjLTQyN2MtYWVlNi1jYTZlYzZlM2JmMGEiLCJleHAiOjE2NTQ2MTc2MDB9.G44W3G7ibppg3mu-j-s6qTGVUca-uSChALoHp1AdHpFW_QgChX4g2iqLBxt9Cz4Dwh1r6PW8bieZTd1TYUXR-TVvOE5Gqo9979pBrI2goLoLq0sHcpsYsdaO7QQFPXM42svr9RWwajZkuBwlztVKyh6IdiUpZbdyCMRW9UPdwfI4q1jDnx0nSJ8Bc0if_p182x_3r7GmX6tkzr7jUX1-voD3rM0v2ev5UZm86lJI0Zq326DGWwP_KAKGgf1IdfbZ2FIDVe6tv8gB5OcWbQaW4wkZFVkFoU5XNTJE8y66XuU0T9Sn1Clu4CDryWvlOsI-gNOuyU__Qkuw3FV-ST8-5A
token: imooc

{
  "username": "qqq",
  "password": "password"
}

### 再发送一个请求
GET http://localhost:9001/imooc/commerce-nacos-client/hystrix/annotation-nacos-info?serviceId=commerce-nacos-client
Content-Type: application/json
Commerce-User: eyJhbGciOiJSUzI1NiJ9.eyJjb21tZXJjZS11c2VyIjoie1wiaWRcIjoxMCxcInVzZXJuYW1lXCI6XCJxcXFcIn0iLCJqdGkiOiI0MmNkZTUwMS01MjZjLTQyN2MtYWVlNi1jYTZlYzZlM2JmMGEiLCJleHAiOjE2NTQ2MTc2MDB9.G44W3G7ibppg3mu-j-s6qTGVUca-uSChALoHp1AdHpFW_QgChX4g2iqLBxt9Cz4Dwh1r6PW8bieZTd1TYUXR-TVvOE5Gqo9979pBrI2goLoLq0sHcpsYsdaO7QQFPXM42svr9RWwajZkuBwlztVKyh6IdiUpZbdyCMRW9UPdwfI4q1jDnx0nSJ8Bc0if_p182x_3r7GmX6tkzr7jUX1-voD3rM0v2ev5UZm86lJI0Zq326DGWwP_KAKGgf1IdfbZ2FIDVe6tv8gB5OcWbQaW4wkZFVkFoU5XNTJE8y66XuU0T9Sn1Clu4CDryWvlOsI-gNOuyU__Qkuw3FV-ST8-5A
token: imooc



